site_name: Documentation
theme:
  logo: assets/merlin_logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode    
      primary: black
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/glenhayoge
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/ghayoge
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/glenhayoge
  


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2018-2024 <a href="https://github.com/glenhayoge"  target="_blank" rel="noopener">Glen Hayoge</a>

